Load image docs link removed
ashirbad29/image-sequencer pull request #1
Opened 2020-09-28 15:49 UTC by ashirbad29

Fixes #0000  (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

2020-09-28 15:59 UTC, HarshKhandeparkar requested changes

2020-09-28 15:59 UTC, HarshKhandeparkar commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step.name === "load-image" || 'href="https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md#') + step.name + '-module">' + (step.description || '') + '</a
Please use `steps['docs-link']` instead of generating the link.

2020-09-28 17:14 UTC, ashirbad29 commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step.name === "load-image" || 'href="https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md#') + step.name + '-module">' + (step.description || '') + '</a
it is steps or step?

2020-09-28 18:21 UTC, HarshKhandeparkar commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step.name === "load-image" || 'href="https://github.com/publiclab/image-sequencer/blob/main/docs/MODULES.md#') + step.name + '-module">' + (step.description || '') + '</a
step. Sorry.

2020-09-29 03:15 UTC, ashirbad29 commented
how should I proceed next, I have to delete this branch and start a new PR right?

2020-09-29 04:39 UTC, HarshKhandeparkar commented
You may edit the branch and it will show up here @ashirbad29

2020-09-29 05:53 UTC, ashirbad29 commented
@HarshKhandeparkar sorry for so many queries _/\_ 
as I am a complete beginner to open source, can you please help me to edit the branch in the browser and create another PR
I am clueless here :(

2020-09-29 05:57 UTC, HarshKhandeparkar commented
Np. Open [ashirbad29/image-sequencer](https://github.com/ashirbad29/image-sequencer/). You can select the branch from the top left corner.
![image](https://user-images.githubusercontent.com/34770591/94517990-ab4f4f80-0246-11eb-9f52-b87195ad4654.png)

Select the branch named `ashirbad29-load-image-docs-link` which is what it is named. Then edit the required file there.

2020-09-29 11:40 UTC, ashirbad29 commented
@HarshKhandeparkar I committed my changes, please review it

2020-09-29 11:58 UTC, HarshKhandeparkar commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
Hmm. Looks good. But can we display a `<p>` when `step['docs-link']` does not exist?

2020-09-29 12:08 UTC, ashirbad29 commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
yes, I guess suggest me where should i put that ```<p>``` and what should be the message inside ```<p>```

2020-09-29 12:21 UTC, HarshKhandeparkar commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
Oh, I just saw that there is a p already. I guess you can just put `step.description` w/o any `<a>`.  Message inside that p should be `step.description`. Ty.

2020-09-29 14:02 UTC, ashirbad29 commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
you are saying I should conditional render the ```<a>``` right?
if there is no link to the docs then i have to simply display the ```<p>```  with ```step.description```, not the link tag

2020-09-29 15:30 UTC, HarshKhandeparkar commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
Yes, precisely.

2020-09-30 11:00 UTC, ashirbad29 commented on examples/lib/defaultHtmlStepUi.js
> +                    '<a ' + (step['docs-link'] ? ('href=' + step['docs-link']) : ('href = "#")) + '>' + (step.description || '') + '</a>' +
I made the changes you suggested, please review

2020-09-30 11:09 UTC, ashirbad29 commented
@HarshKhandeparkar I made changes as per your suggestions, please review it

2020-09-30 13:56 UTC, HarshKhandeparkar approved these changes
LGTM. You may use template strings if you wish but this isn't bad :). The rest of it is not using template strings anyway ¯\_(ツ)_/¯

2020-09-30 14:02 UTC, ashirbad29 commented
yea, it's getting quite a messy, template strings will be clean :)
any suggestion on the code part for me

2020-09-30 14:17 UTC, HarshKhandeparkar commented
Nothing, it's perfect.

2020-09-30 17:16 UTC, ashirbad29 commented
how can i merge this PR?

2020-09-30 17:35 UTC, HarshKhandeparkar commented
Well, neither I nor you can merge. We'll have to wait for a *maintainer*.

2020-09-30 17:38 UTC, merged

2020-09-30 18:04 UTC, HarshKhandeparkar commented
Wait a sec. You opened the PR in your own fork :joy:

2020-10-01 06:24 UTC, ashirbad29 commented
well, I was feeling the same from the beginning, i got confused
now how can i start the pr in the original repo